CREATE TABLE IF NOT EXISTS proptech."DOCUMENTS" (
    "DOCUMENT_ID" UUID PRIMARY KEY,
    "ORIGINAL_FILE_NAME" VARCHAR(500) NOT NULL,
    "STORAGE_KEY" VARCHAR(1000) NOT NULL UNIQUE,
    "STORAGE_URL" VARCHAR(2000),
    "MIME_TYPE" VARCHAR(200) NOT NULL,
    "FILE_SIZE" BIGINT NOT NULL CHECK ("FILE_SIZE" > 0),
    "BUILDING_CODE" VARCHAR(100) NOT NULL,
    "CATEGORY" VARCHAR(200),
    "TITLE" VARCHAR(500),
    "STATUS" VARCHAR(30) NOT NULL,
    "CHUNK_COUNT" INTEGER NOT NULL DEFAULT 0,
    "ERROR_MESSAGE" TEXT,
    "UPLOADED_BY" VARCHAR(200) NOT NULL,
    "CREATED_AT" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "UPDATED_AT" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS proptech."CHAT_CONVERSATIONS" (
    "CONVERSATION_ID" UUID PRIMARY KEY,
    "USER_ID" VARCHAR(200) NOT NULL,
    "BUILDING_CODE" VARCHAR(100) NOT NULL,
    "TITLE" VARCHAR(500) NOT NULL,
    "CREATED_AT" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "UPDATED_AT" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "IS_DELETED" BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS proptech."CHAT_MESSAGES" (
    "MESSAGE_ID" UUID PRIMARY KEY,
    "CONVERSATION_ID" UUID NOT NULL REFERENCES proptech."CHAT_CONVERSATIONS"("CONVERSATION_ID") ON DELETE CASCADE,
    "ROLE" VARCHAR(20) NOT NULL CHECK ("ROLE" IN ('user', 'assistant')),
    "CONTENT" TEXT NOT NULL,
    "SOURCES" JSONB,
    "CREATED_AT" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS "IX_DOCUMENTS_BUILDING_STATUS"
    ON proptech."DOCUMENTS" ("BUILDING_CODE", "STATUS");
CREATE INDEX IF NOT EXISTS "IX_CHAT_CONVERSATIONS_USER_UPDATED"
    ON proptech."CHAT_CONVERSATIONS" ("USER_ID", "UPDATED_AT" DESC);
CREATE INDEX IF NOT EXISTS "IX_CHAT_MESSAGES_CONVERSATION_CREATED"
    ON proptech."CHAT_MESSAGES" ("CONVERSATION_ID", "CREATED_AT");
